### ISSUE TITLE
Demo not compiling on haxe 3.1.3 with hxcpp  3.1.39

### ISSUE THREAD

**Issue by wighawag** [dazKind/hx-nanovg#4]
I got the following error on the demo :

C:\HaxeToolkit\haxe\lib\hx-nanovg/git/hxnanovg/Nvg.hx:3: characters 7-15 : Class not found : cpp.Char

Does hx-nanovg require git version of haxe/hxcpp ?

**Comment by anissen** [comment]
You might want to mention this in the `README.md`. I got the same error as _wighawag_ after following the instructions in the read-me. 

Other than that; keep up the good work! :+1:

**Comment by dazKind** [comment]
Thanks for the input. I just added it
